export const numbersDictionary = [
  'Granát',
  'Jeleň',
  'Noha',
  'Motýľ',
  'Ruža',
  'Sova',
  'Šíp',
  'Kôň',
  'Fľaša',
  'Posteľ',
  'Jaguár',
  'Jojo',
  'Jantár',
  'Jarmok',
  'Jar',
  'Jas',
  'Ješko',
  'Jablko',
  'Jufka',
  'Japonec',
  'Negližé',
  'New Jersey',
  'Nonstop',
  'Nemocnica',
  'Nora',
  'Nos',
  'Náušnice',
  'Nektár',
  'Nufák',
  'Neporiadok',
  'Magnézium',
  'Maják',
  'Minca',
  'Mramor',
  'Marlenka',
  'Mesiac',
  'Myš',
  'Mrak',
  'Mafián',
  'Moped',
  'Rogalo',
  'Roj',
  'Rana',
  'Rambo',
  'Rúra',
  'Rys',
  'Rušeň',
  'Ruka',
  'Referát',
  'Rampa',
  'Segway',
  'Sójový suk',
  'Srna',
  'Somár',
  'Syr',
  'Syseľ',
  'Sušiak',
  'Slamka',
  'Surf',
  'Sopeľ',
  'Šagrén',
  'Šija',
  'Šunka',
  'Šampón',
  'Šerbeľ',
  'Šústie',
  'Šašo',
  'Shrek',
  'Šéf',
  'Šopa',
  'Kengura',
  'Kojot',
  'Konár',
  'Kamera',
  'Kormidlo',
  'Kosť',
  'Kuša',
  'Krkavec',
  'Kufor',
  'Kupón',
  'Figa',
  'Fajka',
  'Fantomas',
  'Farma',
  'Faraón',
  'Festival',
  'Fľaša',
  'Fotka',
  'Famfáry',
  'Filipínec',
  'Pagáč',
  'Pajác',
  'Ponožka',
  'Puma',
  'Parník',
  'Prst',
  'Puška',
  'Pálka',
  'Pifko',
  'Popol'
]

export const stories = {
  '0-9': "Utekám pred výbuchom GRANÁTU, schovám sa do bytovky. Vľavo pri schodoch je JELEŇ s ĽUDSKÝMI NOHAMI. Spoza neho vyletí MOTÝĽ. Ten ma zavedie pred naše dvere a sadne si na RUŽU. V tom mi za chrbtom zahúka SOVA. Sedí na schránkach. Vyletí zľava ŠÍP a zabije sovu, ktorá padá na zem. Cez dvere vojde KÔŇ, ktorom sedí domovník s lukom na chrbte a FĽAŠKOU chľastu v ruke. Zosadne z koňa a ľahne si na POSTEĽ pod schránkami.",
  '10-19': "Idem k našej bytovke. Na parkovisku je odparkovaný nablískaný JAGUÁR, ktorý má namiesto kolies veľké JOJÁ. Pred našou bytovkou sú rozostavané stánky ... v jednom z nich sú povešané JANTÁROVÉ náhrdelníky. Je totižto JARMOK. Nad stánkom je rozkvitnutý strom, pretože je JAR. Ako sa naň dívam, oslepí ma JAS slnka. Cez cestu mi prebehne JEŠKO s JABLKAMI napichnutými na chrbte. Zájde za stánok s kebabom, pred ktorým drží a je JAPONEC JUFKU.",
  '20-29': "Na vešiaku je zavesené NEGLIŽÉ s logom NJD. Príde si ho na seba obliecť Tomáš Tatar. Vychádzam z budovy a na veľkej budove oproti načerveno bliká nápis NONSTOP NEMOCNICA s pokazenými niektorými písmenami. Prejdem ďalej do lesíka a zbadám medvediu NORU, pred ktorou na zemi leží zakrvavený ľudský NOS a vedľa neho ucho s NÁUŠNICOU. Z tieňa norz sa vystrčí medvedí ŇUFÁK zamazaný od NEKTÁRU (medu). Všade naokolo je plno odpadkov (NEPORIADOK)",
  '30-39': "Visím na chytoch. Leziem free solo. Idem si nabrať MAGNÉZIUM na ruky. Leziem na obrovský MAJÁK. Stúpam vyššie, na veľmi malý a tenký stup, ktorým je 50 centová MINCA. Staviam sa na nohe a chytám ďalší chzt, ktorý je veľké madlo vzorované ako MRAMOROM. Keď doleziem, tak už je tma. Na vrchole ma čaká pozlátená MARLENKA. S visiacimi nohami sedím na kraji majáka a hryzkám si marlenku. obzerám pri tom dožlta zafarbený a nezvyčajne veľký MESIAC. Za chrbtom začujem pyskot MYŠI ... keď sa otočím, uvidím ju stáť na stole oňuchávať a obhrýzať marlenku. Mesiac pomaly zakrýva MRAK. Obzerám okolie a dole na pobreží vidím MAFIÁNA (oblek a klobúk - Vito Scaleta). V suke má Thompson 1945 a nasadá na ružový MOPED.",
  '40-49': "Letí chlapík na ROGALE. Do cesty mu vletí obrovský ROJ sršňov. Preto padá cez stromy. V páde sa mu na konáre spraví obrovská RANA cez celú tvár. Záber sa priblíži a ukáže, že chlap je RAMBO (Stalone, tielko, červená šatka na hlave). Pozbiera sa zo zeme a zdvihne hrdzavú RÚRU aby sa pozrel do dialky. Vidí ako po lese pobehuje RYS. Zrazu mu ale cez pohľad prejde vlak s historickým veľkým čiernym parným RUŠŇOM, Z okna lokomotívy sa vystrčí RUKA ukazujúca prostredník. Vzápätí letí z okna kopa papierov, ktorá sa rozletí vzduchom REFERÁT. Vlak má pred sebou veľkú RAMPU, ktorú prerazí a pomaly sa stráca v diaľke.",
  '50-59': "Idem si na SEGWAYI a zobkám si SOJOVÝ SUK. V tom mi vbehne do cesty SRNA. V snahe vyhnúť sa jej zídem z cesty a narazím do SOMÁRA. Keď sa prebúdzam z bezvedomia, pred očami mám SYR ementál. Onedlho na to pribehne SYSEĽ, opatrne oňuchá syr a vezme ho preč. Ja sa teda postavím a idem medzi stromy smerom k moru. Odhrniem kríky a vidím SUŠIAK plný plaviek a uterákov. Ďalej pri mori vidím plážový bar, v ktorom chlapík v havajskej košeli srká cuba libre cey SLAMKU. Idem k moru, ale sú veľké vlny, preto je na mori plno SURFISTOV. Keď sa pozriem na more bližšie, tak zbadám, že je v ňom namiesto vody ťahavý SOPEĽ.",
  '60-69': "Gladiátor si ukladá brnenia zo šAGRÉNOVEJ kože na ŠIJU. Dojedá zvyšky ŠUNKY a vypúšťa vodu plnú ŠAMPÓNU, v ktorej sa kúpal pred bojom. Pred odchodom použije ŠERBEĽ. Po celej zemi arény je roztrúsené husté ŠÚSTIE. V aréne už na neho čaká ŠAŠO Penyvise a ŠREK. Jeho ŠÉF na neho kričí z rohu povzbudzujúce pokriky a zo ŠOPY mu hádže rôzne náčinia, ktoré mu pomôžu v boji.",
  '70-79': "KENGURU na austrálskom pobreží naháňa KOJOT. Potkne sa pri tom o KONÁR. Celé to sníma cestujúci na lodi KAMEROU. Kapitán stojí pri KORMIDLE z KOSTÍ. Ďalší cestujúci sa snaží skoliť KUŠOU KRKAVCA. Keď sa mu to podarí, ide si svoj úlovok schovať do KUFRA. Hneď ako ho otvorí, usmeje sa. Všimne si 30€ KUPÓN do pizza reštaurácie.",
  '80-99': "FIGA padla zo stromu a zhodila FAJKU nič netušiacemu FANTOMASOVI z úst. Mal namierené na kravskú FARMU. Cestou stretol FARAÓNA, ktorý podgurážený išiel z FESTIVALU kostýmov. s FĽAŠOU lacnej vodky si spravili spolu sériu nevydarených FOTIEK. Ako tak fantomas pokračoval, z diaľky začul FAMFÁRY. Keď sa zvedavý prišiel pozrieť na miesto, dostal sa na pompéznu svadbu FILIPÍNSKEHO princa.",
  '90-99': "Mastný PAGÁČ spadol ospalému PAJÁCOVI na špinavú zem plnú bordelu. Ešte že nespadol priamo na hnilú PONOŽKU, ktorá je na zemi od minulej jari. Prezerá si fotky, ktoré mu nosia kamaráti. PUMA odfotené v skoku v Severnej Amerike. Trochu pripomína logo športovej značky. Na ďalšej je vtipná fotomontáž PARNÍKU Lusitánia, v ktorej sa miesto komínov týčia dymiace PRSTY. Ani sám nevie, čo mu na tom príde vtipné. Po nevydarenom štarte do dňa si ide zahrať obľúbenú hru. Princíp je v tom, že jeden spoluhráč strieľa holuby PUŠKOU a druhý musí v páde odpáliť holuba drevenou PÁLKOU. Už sa teší ako po hre skončí na jedno chladené PIFKO. Po ceste však do neho trafí blesk a na ceste po ňom ostane len smradľavý POPOL a mastný pagáč.",
}